services:
  redis:
    image: redis:8.4.0-alpine3.22
    container_name: springboot-sns-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  postgres:
    image: postgres:18.1-alpine3.22
    container_name: springboot-sns-postgres
    environment:
      POSTGRES_DB: snsdb
      POSTGRES_USER: snsuser
      POSTGRES_PASSWORD: snspassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U snsuser -d snsdb"]
      interval: 10s
      timeout: 3s
      retries: 3

  rustfs:
    image: rustfs/rustfs:1.0.0-alpha.72
    container_name: springboot-sns-rustfs
    environment:
      RUSTFS_ADDRESS: 0.0.0.0:9000
      RUSTFS_CONSOLE_ADDRESS: 0.0.0.0:9001 # RustFS Web Console
      RUSTFS_CONSOLE_ENABLE: "true"
      RUSTFS_ACCESS_KEY: rustfsadmin
      RUSTFS_SECRET_KEY: rustfsadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - rustfs-data:/data
      - rustfs-logs:/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9000/health"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  redis-data:
    driver: local
  postgres-data:
    driver: local
  rustfs-data:
    driver: local
  rustfs-logs:
    driver: local
